### PR TITLE
Update usage of tinyssh-convert

### LINKED ISSUE #10: tinyssh-convert usage error
The CLI for `tinyssh-convert` was (recently?) changed. Currently, trying to use this package causes:

```
  -> Running build hook: [tinyssh]
tinyssh-convert: usage: tinyssh-convert out-tinysshkeydir < in-opensshfile
```

https://github.com/grazzolini/mkinitcpio-tinyssh/blob/bd73e32a1685bb843cdfe1300abcad58faba6e88/tinyssh_install#L32

### PR DESCRIPTION
**Pull request by jennydaman**
Fixes #10 

I edited `/usr/lib/initcpio/install/tinyssh` by hand on my own system to test this patch.

### CODE REVIEW

**Comment by wilsoniya** [comment]
@grazzolini this repo appears to be broken relative to updates to `tinyssh-convert` which seems to have broken the contract expected this package. 

If you could amend this branch with the additions described here: https://github.com/grazzolini/mkinitcpio-tinyssh/issues/10#issuecomment-1104450881 I think your much appreciated hook will be back in working order. Thank you!

Here's a link to `tinyssh-convert` in the current state: https://github.com/janmojzis/tinyssh/blob/master/tools/tinyssh-convert#L89 - notice it doesn't take any named flags, only positional arguments

**Comment by svenstaro** [comment]
@grazzolini ping

**Comment by grazzolini** [comment]
This looks ok to me and it also closes #9

**Comment by svenstaro** [comment]
@grazzolini Thanks! Can you pop out a short release with that and also update the Arch package?

**Comment by grazzolini** [comment]
Yes, I'm preparing a release. Just testing this on my remote server.

**Comment by cmm1107** [comment]
Great to see this merged after 3 years and 21 days :+1:

**Pull request merged**
